version: 2
updates:
  - package-ecosystem: "github-actions"
    schedule:
        interval: "weekly"
    directory: "/"
  - package-ecosystem: "cargo"
    schedule:
        interval: "weekly"
    directory: "/"
  - package-ecosystem: "docker"
    schedule:
        interval: "weekly"
    directory: "/"
